export const Facilities = [
  { id: 1, title: "آسانسور", value: "elevator" },
  { id: 2, title: "پارکینگ", value: "parking" },
  { id: 3, title: "کولر گازی", value: "air_conditioner" },
  { id: 4, title: "تراس", value: "balcony" },
  { id: 5, title: "نقاشی ساختمان", value: "painting" },
  { id: 6, title: "انباری", value: "ware_house" },
  { id: 7, title: "کولر آبی", value: "water_coller" },
  { id: 8, title: "کاغذ دیواری", value: "wallpaper" },
  { id: 9, title: "سرویس فرنگی", value: "toilet_service" },
  { id: 10, title: "آیفون تصویری", value: "iphone" },
  { id: 11, title: "روف گاردن", value: "roof_garden" },
  { id: 12, title: "دوربین مداربسته", value: "CCTV_camera" },
  { id: 13, title: "گاز رومیزی", value: "table_gas" },
  { id: 14, title: "کمد دیواری", value: "wardrobe" },
  { id: 15, title: "رادیاتور", value: "radiator" },
  { id: 16, title: "شوفاژ", value: "heating" },
  { id: 17, title: "پکیج", value: "package" },
  { id: 18, title: "چیلر", value: "chiller" },
  { id: 19, title: "آب گرمکن", value: "water_heater" },
  { id: 20, title: "حمام مستر", value: "master_bathroom" },
  { id: 21, title: "سونا", value: "sauna" },
  { id: 22, title: "جکوزی", value: "jacuzzi" },
  { id: 23, title: "سالن ورزش", value: "gym" },
  { id: 24, title: "لابی", value: "lobby" },
  { id: 25, title: "درب ضد سرقت", value: "anti_theft_door" },
  { id: 26, title: "سیستم گرمایش از کف", value: "underfloor_heating" },
];
